[package]
name = "xfft"
version = "0.1.0"
edition = "2021"
authors = ["Keith Cullen <12213462+keith-cullen@users.noreply.github.com>"]
description = "A library of Fast Fourier Transforms"
license = "Apache-2.0"

[dependencies]
